# Generated by Django 3.2.9 on 2021-12-10 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, max_length=64, verbose_name='Vin')),
                ('color', models.CharField(max_length=15, verbose_name='Color')),
                ('brand', models.CharField(max_length=30, verbose_name='Brand')),
                ('car_type', models.CharField(choices=[(1, 'Sedan'), (2, 'Hatchback'), (3, 'Universal'), (4, 'Coupe')], max_length=8, verbose_name='Car type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
